Remove catalog and stabilities, part 2
flox/pkgdb pull request #110
Opened 2023-10-30 21:10 UTC by garbas

Fixes #108

2023-10-31 15:10 UTC, aakropotkin requested changes
We need to bump the SQL schema version, but other than that this looks good.
There's some instructions in CONTRIBUTING that explain how.
You'll only bump the "views" version for this.

2023-11-01 15:11 UTC, aakropotkin requested changes

2023-11-01 15:11 UTC, aakropotkin commented on include/flox/pkgdb/read.hh
> +constexpr SqlVersions sqlVersions = { .tables = 3, .views = 2 };
```suggestion
constexpr SqlVersions sqlVersions = { .tables = 2, .views = 3 };
```

2023-11-01 15:14 UTC, aakropotkin approved these changes

2023-11-01 15:56 UTC, merged

2023-11-02 11:31 UTC, garbas commented
❤️